//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoDA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public Servico()
        {
        }

        public int IdServico { get; set; }
        public string Descricao { get; set; }
        public int Valor { get; set; }
        public string Unidades { get; set; }
        public int LimpezaIdLimpeza { get; set; }
        public int Valor_total { get; set; }
    
        public virtual Limpeza Limpeza { get; set; }
    }
}
